package com.pankx.dao;

import com.pankx.bean.UType;
import com.pankx.bean.UTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface UTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_utype
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    int countByExample(UTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_utype
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    int deleteByExample(UTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_utype
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    int deleteByPrimaryKey(Integer utypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_utype
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    int insert(UType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_utype
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    int insertSelective(UType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_utype
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    List<UType> selectByExample(UTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_utype
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    UType selectByPrimaryKey(Integer utypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_utype
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") UType record, @Param("example") UTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_utype
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    int updateByExample(@Param("record") UType record, @Param("example") UTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_utype
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    int updateByPrimaryKeySelective(UType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_utype
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    int updateByPrimaryKey(UType record);
}