package com.pankx.bean;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.user_id
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.user_name
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.gender
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.email
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.ut_id
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    private Integer utId;

    private UType uType;

    public User(Integer userId, String userName, String gender, String email, Integer utId) {
        this.userId = userId;
        this.userName = userName;
        this.gender = gender;
        this.email = email;
        this.utId = utId;
    }
    public User(){
        super();
    }

    public UType getuType() {
        return uType;
    }

    public void setuType(UType uType) {
        this.uType = uType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.user_id
     *
     * @return the value of tbl_user.user_id
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.user_id
     *
     * @param userId the value for tbl_user.user_id
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.user_name
     *
     * @return the value of tbl_user.user_name
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.user_name
     *
     * @param userName the value for tbl_user.user_name
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.gender
     *
     * @return the value of tbl_user.gender
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.gender
     *
     * @param gender the value for tbl_user.gender
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.email
     *
     * @return the value of tbl_user.email
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.email
     *
     * @param email the value for tbl_user.email
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.ut_id
     *
     * @return the value of tbl_user.ut_id
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    public Integer getUtId() {
        return utId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.ut_id
     *
     * @param utId the value for tbl_user.ut_id
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    public void setUtId(Integer utId) {
        this.utId = utId;
    }

    @Override
    public String toString() {
        return "User{" +
                "userId=" + userId +
                ", userName='" + userName + '\'' +
                ", gender='" + gender + '\'' +
                ", email='" + email + '\'' +
                ", utId=" + utId +
                ", uType=" + uType +
                '}';
    }
}