package com.pankx.bean;

public class UType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_utype.utype_id
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    private Integer utypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_utype.utype_name
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    private String utypeName;

    public UType(Integer utypeId, String utypeName) {
        this.utypeId = utypeId;
        this.utypeName = utypeName;
    }

    public UType(){
        super();
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_utype.utype_id
     *
     * @return the value of tbl_utype.utype_id
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    public Integer getUtypeId() {
        return utypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_utype.utype_id
     *
     * @param utypeId the value for tbl_utype.utype_id
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    public void setUtypeId(Integer utypeId) {
        this.utypeId = utypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_utype.utype_name
     *
     * @return the value of tbl_utype.utype_name
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    public String getUtypeName() {
        return utypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_utype.utype_name
     *
     * @param utypeName the value for tbl_utype.utype_name
     *
     * @mbggenerated Thu Mar 26 23:28:15 CST 2020
     */
    public void setUtypeName(String utypeName) {
        this.utypeName = utypeName == null ? null : utypeName.trim();
    }

    @Override
    public String toString() {
        return "UType{" +
                "utypeId=" + utypeId +
                ", utypeName='" + utypeName + '\'' +
                '}';
    }
}